# Generated by Django 5.1 on 2024-08-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_shoppinglist_shoppinglistitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="unit",
            new_name="measurement_unit",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="title",
            new_name="name",
        ),
    ]
