# Generated by Django 5.1 on 2024-08-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"),
                name="unique_recipe_ingredient",
            ),
        ),
    ]
