# Generated by Django 5.1 on 2024-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_rename_unit_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="recipes/images/",
                verbose_name="Изображение рецепта",
            ),
        ),
    ]
