# Generated by Django 5.1 on 2024-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_recipe_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                max_length=150, verbose_name="Единица измерения"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Название ингредиента"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Название рецепта"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Тег рецепта"),
        ),
    ]
