# Generated by Django 5.1 on 2024-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_rename_description_recipe_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="food.tag"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                max_length=25, verbose_name="Название рецепта"
            ),
        ),
    ]
