# Generated by Django 5.1 on 2024-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_recipe_cooking_time_recipe_tags_alter_recipe_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredients",
            old_name="quantity",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="shoppinglistitem",
            old_name="quantity",
            new_name="amount",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Название рецепта"
            ),
        ),
    ]
