# Generated by Django 5.1 on 2024-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_recipe_cooking_time_recipe_tags_alter_recipe_name"),
        ("users", "0005_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_recipes",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_favorite_recipes",
                to="food.recipe",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="shopping_cart",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_shopping_cart",
                to="food.recipe",
            ),
        ),
    ]
