# Generated by Django 5.1 on 2024-08-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_favorite_recipes_customuser_shopping_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="created_at",
        ),
    ]
