# Generated by Django 5.1 on 2024-08-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_subscription_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="favorite_recipes",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="shopping_cart",
        ),
    ]
